--------------------------------------------------------
-- Archivo creado  - martes-septiembre-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAJERO
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."CAJERO" 
   (	"NUMERO" NUMBER, 
	"EMPLEADO" NUMBER, 
	"CLIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Table CLIENTES_SISBAN
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."CLIENTES_SISBAN" 
   (	"COD_CLIENTE" NUMBER, 
	"NUMERO_CEDULA" VARCHAR2(20 BYTE), 
	"ROSTRO_CLIENTE" BLOB, 
	"NOMBRES" VARCHAR2(60 BYTE), 
	"APELLIDOS" VARCHAR2(60 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" 
 LOB ("ROSTRO_CLIENTE") STORE AS BASICFILE (
  TABLESPACE "SISBAN" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."CUENTA" 
   (	"COD_CUENTA" NUMBER, 
	"CLIENTE" NUMBER, 
	"TIPO" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"SALDO_CONTABLE" NUMBER, 
	"SALDO_DISPONIBLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;

   COMMENT ON COLUMN "ADMINSB"."CUENTA"."TIPO" IS 'CORRIENTE/AHORRO';
   COMMENT ON COLUMN "ADMINSB"."CUENTA"."ESTADO" IS 'activa/inactiva';
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."DEPARTAMENTO" 
   (	"CODIGO" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."EMPLEADO" 
   (	"COD" NUMBER, 
	"DEPARTAMENTO" NUMBER, 
	"CEDULA" VARCHAR2(20 BYTE), 
	"ROSTRO" BLOB, 
	"NOMBRES" VARCHAR2(60 BYTE), 
	"APELLIDOS" VARCHAR2(60 BYTE), 
	"FECHA_NAC" DATE, 
	"DIRECCION" VARCHAR2(60 BYTE), 
	"TELEFONO" VARCHAR2(30 BYTE), 
	"CARGO" VARCHAR2(30 BYTE), 
	"FECHA_INGRE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" 
 LOB ("ROSTRO") STORE AS BASICFILE (
  TABLESPACE "SISBAN" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."MOVIMIENTOS" 
   (	"DOCUMENTO" NUMBER, 
	"CAJA" NUMBER, 
	"CUENTA" NUMBER, 
	"CONCEPTO" VARCHAR2(200 BYTE), 
	"TIPO" VARCHAR2(30 BYTE), 
	"MONTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;

   COMMENT ON COLUMN "ADMINSB"."MOVIMIENTOS"."CONCEPTO" IS 'Descripcion de lo que se realizao';
   COMMENT ON COLUMN "ADMINSB"."MOVIMIENTOS"."TIPO" IS 'deposito/retiro';
--------------------------------------------------------
--  DDL for Table REGISTROS_SESIONES
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."REGISTROS_SESIONES" 
   (	"SESION_ID_USUARIO" VARCHAR2(50 BYTE), 
	"SESION_FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "ADMINSB"."USUARIOS" 
   (	"COD_USU" NUMBER, 
	"EMPLEADO" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"CONTRASENA" VARCHAR2(200 BYTE), 
	"NIVEL_ACCESO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;

   COMMENT ON COLUMN "ADMINSB"."USUARIOS"."NIVEL_ACCESO" IS '0,1,2,3';
REM INSERTING into ADMINSB.CAJERO
SET DEFINE OFF;
REM INSERTING into ADMINSB.CLIENTES_SISBAN
SET DEFINE OFF;
REM INSERTING into ADMINSB.CUENTA
SET DEFINE OFF;
REM INSERTING into ADMINSB.DEPARTAMENTO
SET DEFINE OFF;
Insert into ADMINSB.DEPARTAMENTO (CODIGO,NOMBRE) values ('1','TECNOLOGIA_SEGURIDAD');
REM INSERTING into ADMINSB.EMPLEADO
SET DEFINE OFF;
Insert into ADMINSB.EMPLEADO (COD,DEPARTAMENTO,CEDULA,NOMBRES,APELLIDOS,FECHA_NAC,DIRECCION,TELEFONO,CARGO,FECHA_INGRE) values ('1','1','999999999','ADMIN','ADMIN',to_date('28/09/2020','DD/MM/RRRR'),'SISBAN','0999999','ADMINISTRADOR_SISTEMA',to_date('28/09/2020','DD/MM/RRRR'));
REM INSERTING into ADMINSB.MOVIMIENTOS
SET DEFINE OFF;
REM INSERTING into ADMINSB.REGISTROS_SESIONES
SET DEFINE OFF;
REM INSERTING into ADMINSB.USUARIOS
SET DEFINE OFF;
Insert into ADMINSB.USUARIOS (COD_USU,EMPLEADO,NOMBRE,CONTRASENA,NIVEL_ACCESO) values ('1','1','ADMIN','ADMIN','0');
--------------------------------------------------------
--  DDL for Index CUENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINSB"."CUENTA_PK" ON "ADMINSB"."CUENTA" ("COD_CUENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Index MOVIMIENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINSB"."MOVIMIENTOS_PK" ON "ADMINSB"."MOVIMIENTOS" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINSB"."EMPLEADO_PK" ON "ADMINSB"."EMPLEADO" ("COD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINSB"."USUARIOS_PK" ON "ADMINSB"."USUARIOS" ("COD_USU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Index CAJERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINSB"."CAJERO_PK" ON "ADMINSB"."CAJERO" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINSB"."DEPARTAMENTO_PK" ON "ADMINSB"."DEPARTAMENTO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN" ;
--------------------------------------------------------
--  Constraints for Table CAJERO
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."CAJERO" ADD CONSTRAINT "CAJERO_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN"  ENABLE;
  ALTER TABLE "ADMINSB"."CAJERO" MODIFY ("CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."CAJERO" MODIFY ("EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."CAJERO" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("COD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN"  ENABLE;
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("FECHA_INGRE" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("CARGO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("FECHA_NAC" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."EMPLEADO" MODIFY ("COD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTOS_PK" PRIMARY KEY ("DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN"  ENABLE;
  ALTER TABLE "ADMINSB"."MOVIMIENTOS" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."MOVIMIENTOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."MOVIMIENTOS" MODIFY ("CONCEPTO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."MOVIMIENTOS" MODIFY ("CUENTA" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."MOVIMIENTOS" MODIFY ("CAJA" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."MOVIMIENTOS" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN"  ENABLE;
  ALTER TABLE "ADMINSB"."DEPARTAMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."DEPARTAMENTO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("COD_USU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN"  ENABLE;
  ALTER TABLE "ADMINSB"."USUARIOS" MODIFY ("NIVEL_ACCESO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."USUARIOS" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."USUARIOS" MODIFY ("EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."USUARIOS" MODIFY ("COD_USU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES_SISBAN
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."CLIENTES_SISBAN" ADD PRIMARY KEY ("COD_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."CUENTA" ADD CONSTRAINT "CUENTA_PK" PRIMARY KEY ("COD_CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISBAN"  ENABLE;
  ALTER TABLE "ADMINSB"."CUENTA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."CUENTA" MODIFY ("CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMINSB"."CUENTA" MODIFY ("COD_CUENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CAJERO
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."CAJERO" ADD CONSTRAINT "CLIENTE_FK" FOREIGN KEY ("CLIENTE")
	  REFERENCES "ADMINSB"."CLIENTES_SISBAN" ("COD_CLIENTE") ENABLE;
  ALTER TABLE "ADMINSB"."CAJERO" ADD CONSTRAINT "EMPLE_FK" FOREIGN KEY ("EMPLEADO")
	  REFERENCES "ADMINSB"."EMPLEADO" ("COD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."CUENTA" ADD CONSTRAINT "CUENTA_FK1" FOREIGN KEY ("CLIENTE")
	  REFERENCES "ADMINSB"."CLIENTES_SISBAN" ("COD_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."EMPLEADO" ADD CONSTRAINT "DEPARTAMENTO_FK" FOREIGN KEY ("DEPARTAMENTO")
	  REFERENCES "ADMINSB"."DEPARTAMENTO" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTOS_FK1" FOREIGN KEY ("CAJA")
	  REFERENCES "ADMINSB"."CAJERO" ("NUMERO") ENABLE;
  ALTER TABLE "ADMINSB"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTOS_FK2" FOREIGN KEY ("CUENTA")
	  REFERENCES "ADMINSB"."CUENTA" ("COD_CUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ADMINSB"."USUARIOS" ADD CONSTRAINT "EMPLEADO_FK" FOREIGN KEY ("EMPLEADO")
	  REFERENCES "ADMINSB"."EMPLEADO" ("COD") ENABLE;
